import type { ActivityRecord, LeadRecord, PropertyRecord } from './estateflow-types';

export const demoLeads: LeadRecord[] = [
  {
    id: 'lead-1',
    full_name: 'Rahul Sharma',
    phone: '+919999999999',
    email: 'rahul@example.com',
    source: '36 Acre',
    property_type: 'Apartment',
    budget_min: 7500000,
    budget_max: 12000000,
    preferred_location: 'Gurgaon',
    notes: 'Looking for 3BHK near Golf Course Road',
    status: 'New',
    temperature: 'Hot',
    assigned_agent_id: 'agent-1',
    next_followup: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
    last_contacted_at: null,
  },
  {
    id: 'lead-2',
    full_name: 'Sneha Gupta',
    phone: '+919888888888',
    email: 'sneha@example.com',
    source: 'Facebook',
    property_type: 'Villa',
    budget_min: 20000000,
    budget_max: 30000000,
    preferred_location: 'Gurgaon',
    notes: 'Family needs a 4BHK with garden',
    status: 'Contacted',
    temperature: 'Warm',
    assigned_agent_id: 'agent-2',
    next_followup: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
    last_contacted_at: new Date().toISOString(),
  },
  {
    id: 'lead-3',
    full_name: 'Aman Verma',
    phone: '+919777777777',
    email: 'aman@example.com',
    source: 'Website',
    property_type: 'Commercial',
    budget_min: 4500000,
    budget_max: 8000000,
    preferred_location: 'Noida',
    notes: 'Office space for startup',
    status: 'Interested',
    temperature: 'Cold',
    assigned_agent_id: 'agent-1',
    next_followup: null,
    created_at: new Date().toISOString(),
    last_contacted_at: null,
  },
];

export const demoProperties: PropertyRecord[] = [
  {
    id: 'property-1',
    title: 'Golf View 3BHK',
    location: 'Gurgaon',
    address: 'Near Golf Course Road',
    latitude: 28.4595,
    longitude: 77.0266,
    property_type: 'Apartment',
    price: 9500000,
    size: '1500 sqft',
    bedrooms: 3,
    bathrooms: 3,
    floor: '12th',
    furnishing: 'Semi Furnished',
    availability_status: 'Available',
    description: 'Premium apartment with clubhouse and balcony views.',
    amenities: ['Clubhouse', 'Pool', 'Gym', 'Parking'],
    owner_info: { name: 'Alpha Developers' },
    tags: ['hot', 'near-metro'],
    units_available: 4,
    created_at: new Date().toISOString(),
  },
  {
    id: 'property-2',
    title: 'Green Villa',
    location: 'Gurgaon',
    address: 'Sector 55',
    latitude: 28.4239,
    longitude: 77.1025,
    property_type: 'Villa',
    price: 25000000,
    size: '3500 sqft',
    bedrooms: 4,
    bathrooms: 5,
    floor: 'G+2',
    furnishing: 'Fully Furnished',
    availability_status: 'Available',
    description: 'Spacious villa with private garden and rooftop deck.',
    amenities: ['Garden', 'Terrace', 'Security'],
    owner_info: { name: 'Prime Estates' },
    tags: ['luxury'],
    units_available: 1,
    created_at: new Date().toISOString(),
  },
];

export const demoTimeline: ActivityRecord[] = [
  {
    id: 'activity-1',
    type: 'lead_created',
    payload: { message: 'Lead entered from 36 Acre' },
    created_at: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'activity-2',
    type: 'call_completed',
    payload: { message: 'Connected agent and lead on a live call' },
    created_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    id: 'activity-3',
    type: 'property_shared',
    payload: { message: 'Shared Golf View 3BHK in WhatsApp' },
    created_at: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
  },
];
